### ISSUE TITLE
Installer on the release page does not link to the right maven location

### ISSUE THREAD

**Issue by FinnT730** [panda-lang/installer#20]
The link on the releases tab does not link to the installer, and instead I get a 404.
I did some digging on the public maven, and found it. seems it was just moved
[Link to the new Maven endpoint](https://repo.panda-lang.org/#/releases/org/panda-lang/installer/1.0.1)
[Link to the old, broken one](https://repo.panda-lang.org/org/panda-lang/installer/1.0.1/panda-installer-1.0.1.exe)

**Comment by dzikoysk** [comment]
Thanks! Right, I've updated Reposilite 2.x to 3.x lately and I'm still working on that and I didn't have time to update all of them for panda-lang organization. Do you want to make PR? :)

**Comment by FinnT730** [comment]
> Do you want to make PR?

I might when I have time today / next week.
If I don't sorry about that then :)

Also, is the installer supposed to take very long trying to install? Since it does not look like it is doing much. Maybe a bug?

**Comment by dzikoysk** [comment]
This installer is quite a mess and in the future should be replaced with something lightweight in e.g. Rust, but it's not a priority for me know, so that's fine :)
