### ISSUE TITLE
Joint Effort

### ISSUE THREAD

**Issue by leaanthony** [panda-lang/installer#3]
Hi there!

Nice project! I am planning on building a generic installer framework using Wails as I see a great need for it. I'd like to help out however I can on this project as i think it would benefit us both. Let me know your thoughts!

**Comment by dzikoysk** [comment]
We've finally decided to use Electron. Libraries in Rust and Go looks great, but they still have some disadvantages. We also don't have enough resources to focus on installer as a standalone platform/framework.

We're not saying `no` to Wails, we just need more time and involvement from the community in the future to let it happen.
